version: "3.4"
services:
  www:
    build:
      context: ./client
      args:
        - AUTH_HOST=https://staging.accounts.crcsi.com.au
        - QA4L_CRCSI_ACCOUNTS_CLIENT_ID=720174
    environment:
      - NODE_ENV=production
    ports:
      - '80:80'

  api:
    build:
      context: ./server
    env_file: ./server.conf
    environment:
      - ENVIRONMENT=production
