version: "3.4"
services:
  www:
    build:
      context: ./client
      args:
        - AUTH_HOST=https://ausseabed-staging.auth.ap-southeast-2.amazoncognito.com
        - AUTH_CLIENT_ID=63r1aleijsut3g9tq9hkr0p424
    environment:
      - NODE_ENV=production
    ports:
      - '80:80'

  api:
    build:
      context: ./server
    env_file: ./server.conf
    environment:
      - ENVIRONMENT=production
