version: "3.4"
services:
  www:
    build:
      context: ./client
    environment:
      - VIRTUAL_HOST=qa4mbes.vcap.me
      - AUTH_HOST=https://staging.accounts.crcsi.com.au
      - NODE_ENV=production

  api:
    build:
      context: ./server
    env_file: ../config/server.conf
    environment:
      - ENVIRONMENT=production

  proxy:
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - '80:80'