version: "3.4"
services:
  www:
    build:
      context: ./client
    environment:
      - NODE_ENV=production
    ports:
      - '80:80'

  api:
    build:
      context: ./server
    env_file: ./server.conf
    environment:
      - ENVIRONMENT=production
