version: "3.4"
services:

  www:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: .dockerenv
    ports:
      - '3001:3001'
    depends_on:
      - 'api'

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ../config/server.conf
    environment:
      POSTGRES_HOSTNAME: "db-postgres"
    ports:
      - '3000:3000'
    depends_on:
      - 'db-postgres'
      - 'db-dynamo'

  db-postgres:
    image: mdillon/postgis:9.6
    env_file: .dockerenv
    ports:
      - '5432:5432'

  db-dynamo:
    image: amazon/dynamodb-local
    ports:
      - '5433:5433'
    environment:
      - ./Djava.library.path=./DynamoDBLocal_lib
    volumes:
      - ../dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data", "-port", "5433"]
