version: "3.4"
services:

  www:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: .dockerenv
    depends_on:
      - 'api'

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server.conf
    environment:
      POSTGRES_HOSTNAME: "db-postgres"
    depends_on:
      - 'db-postgres'

  db-postgres:
    image: mdillon/postgis:9.6
    env_file: ./server.conf
