version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps@sha256:f15719b269c2c7337d2fb29a31abf4edcfe30311291765b831e699b0ad9ae77d

jobs:
  build:
    parameters:
      image-name:
        type: string
      image-tag-suffix:
        type: string
      image-file:
        type: string
      docker-file-path:
        type: string
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set env vars
          command: export SHORT_GIT_HASH="$(echo "$CIRCLE_SHA1" | cut -c -7)"
      - run:
          name: Build << parameters.image-name >> Docker image
          command: docker build -t << parameters.image-name >>:$SHORT_GIT_HASH<< parameters.image-tag-suffix >> --build-arg AUTH_HOST=https://staging.accounts.crcsi.com.au --build-arg AUTH_CLIENT_ID=720174 << parameters.docker-file-path >>
      - run:
          name: Tagging << parameters.image-name >> Docker image
          command: docker tag << parameters.image-name >>:$SHORT_GIT_HASH<< parameters.image-tag-suffix >> << parameters.image-name >>:latest<< parameters.image-tag-suffix >>
      - run:
          name: Archive API Docker image
          command: docker save -o << parameters.image-file >> << parameters.image-name >>
      - persist_to_workspace:
          root: .
          paths:
            - ./<< parameters.image-file >>

  publish:
    parameters:
      image-name:
        type: string
      image-tag-suffix:
        type: string
      image-file:
        type: string
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived << parameters.image-file >> Docker image
          command: docker load -i /tmp/workspace/<< parameters.image-file >>
      - run:
          name: Publish Docker Images to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push << parameters.image-name >>


workflows:
  version: 2
  build-develop:
    jobs:
      - build:
          name: build-api-develop
          image-name: ausseabed/spt-api
          image-tag-suffix: '-beta'
          image-file: image-api.tar
          docker-file-path: server
          filters:
            branches:
              only: develop
      - publish:
          name: publish-api-develop
          image-name: ausseabed/spt-api
          image-tag-suffix: '-beta'
          image-file: image-api.tar
          requires:
            - build-api-develop
          filters:
            branches:
              only: develop
      - build:
          name: build-www-develop
          image-name: ausseabed/spt-www
          image-tag-suffix: '-beta'
          image-file: image-www.tar
          docker-file-path: client
          filters:
            branches:
              only: develop
      - publish:
          name: publish-www-develop
          image-name: ausseabed/spt-www
          image-tag-suffix: '-beta'
          image-file: image-www.tar
          requires:
            - build-www-develop
          filters:
            branches:
              only: develop
      - build:
          name: build-mapserver-develop
          image-name: ausseabed/spt-mapserver
          image-tag-suffix: '-beta'
          image-file: image-mapserver.tar
          docker-file-path: map
          filters:
            branches:
              only: develop
      - publish:
          name: publish-mapserver-develop
          image-name: ausseabed/spt-mapserver
          image-tag-suffix: '-beta'
          image-file: image-mapserver.tar
          requires:
            - build-mapserver-develop
          filters:
            branches:
              only: develop
