version: 2
jobs:
  build-api:
    environment:
      IMAGE_NAME: crcsi/qa4mbes-api
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build API Docker image
          command: docker build -t crcsi/qa4mbes-api:develop --build-arg AUTH_HOST=https://staging.accounts.crcsi.com.au/ --build-arg AUTH_CLIENT_ID=720174 server

  build-www:
    environment:
      IMAGE_NAME: crcsi/qa4mbes-www
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build WWW Docker image
          command: docker build -t crcsi/qa4mbes-www:develop --build-arg AUTH_HOST=https://staging.accounts.crcsi.com.au/ --build-arg AUTH_CLIENT_ID=720174 client


workflows:
  version: 2
  build-develop:
    jobs:
      - build-api:
          filters:
            branches:
              only: develop
      - build-www:
          filters:
            branches:
              only: develop
