version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME_API: crcsi/qa4mbes-api
      IMAGE_NAME_WWW: crcsi/qa4mbes-www
    docker:
      - image: circleci/buildpack-deps@sha256:f15719b269c2c7337d2fb29a31abf4edcfe30311291765b831e699b0ad9ae77d

jobs:
  build-api:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build API Docker image
          command: docker build -t $IMAGE_NAME_API:develop --build-arg AUTH_HOST=https://staging.accounts.crcsi.com.au --build-arg AUTH_CLIENT_ID=720174 server
      - run:
          name: Archive API Docker image
          command: docker save -o image-api.tar $IMAGE_NAME_API
      - persist_to_workspace:
          root: .
          paths:
            - ./image-api.tar

  build-www:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build WWW Docker image
          command: docker build -t $IMAGE_NAME_WWW:develop --build-arg AUTH_HOST=https://staging.accounts.crcsi.com.au --build-arg AUTH_CLIENT_ID=720174 client
      - run:
          name: Archive WWW Docker image
          command: docker save -o image-www.tar $IMAGE_NAME_WWW
      - persist_to_workspace:
          root: .
          paths:
            - ./image-www.tar


  publish-develop:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived API Docker image
          command: docker load -i /tmp/workspace/image-api.tar
      - run:
          name: Load archived WWW Docker image
          command: docker load -i /tmp/workspace/image-www.tar
      - run:
          name: Publish Docker Images to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME_WWW:develop
            docker push $IMAGE_NAME_API:develop


workflows:
  version: 2
  build-develop:
    jobs:
      - build-api:
          filters:
            branches:
              only: develop
      - build-www:
          filters:
            branches:
              only: develop
      - publish-develop:
          requires:
            - build-api
            - build-www
          filters:
            branches:
              only: develop
