version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps@sha256:f15719b269c2c7337d2fb29a31abf4edcfe30311291765b831e699b0ad9ae77d

jobs:
  build:
    parameters:
      image-name:
        type: string
      image-tag:
        type: string
      image-file:
        type: string
      docker-file-path:
        type: string
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build API Docker image
          command: docker build -t << parameters.image-name >>:<< parameters.image-tag >> --build-arg AUTH_HOST=https://staging.accounts.crcsi.com.au --build-arg AUTH_CLIENT_ID=720174 << parameters.docker-file-path >>
      - run:
          name: Archive API Docker image
          command: docker save -o << parameters.image-file >> << parameters.image-name >>
      - persist_to_workspace:
          root: .
          paths:
            - ./<< parameters.image-file >>

  publish-develop:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived API Docker image
          command: docker load -i /tmp/workspace/image-api.tar
      - run:
          name: Load archived WWW Docker image
          command: docker load -i /tmp/workspace/image-www.tar
      - run:
          name: Load archived MapServer Docker image
          command: docker load -i /tmp/workspace/image-mapserver.tar
      - run:
          name: Publish Docker Images to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME_WWW:develop
            docker push $IMAGE_NAME_API:develop
            docker push $IMAGE_NAME_MAPSERVER:develop

workflows:
  version: 2
  build-develop:
    jobs:
      - build:
          image-name: crcsi/qa4mbes-api
          image-tag: develop
          image-file: image-api.tar
          docker-file-path: server
          filters:
            branches:
              only: develop
      - build:
          image-name: crcsi/qa4mbes-www
          image-tag: develop
          image-file: image-www.tar
          docker-file-path: client
          filters:
            branches:
              only: develop
      - build:
          image-name: crcsi/qa4mbes-mapserver
          image-tag: develop
          image-file: image-mapserver.tar
          docker-file-path: map
          filters:
            branches:
              only: develop
      - publish-develop:
          requires:
            - build
          filters:
            branches:
              only: develop
